on:
 push:
   branches:
     - master








jobs:
 bulid:
   runs-on: ubuntu-latest

   steps:
     - name: 'Testing Github action'
       run: pwd

     - name: 'Testing printing'
       run: echo raneem  